config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
  	get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root 'groups#index'

  resources :groups do
    resources :comments
  end

  resources :users do
    collection do
      post ':id/follow' => 'users#follow', as: :follow
      post ':id/unfollow' => 'users#unfollow', as: :unfollow
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/group.rb
class Group < ApplicationRecord
    acts_as_followable
    has_many :comments, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }  
  has_many :comments, dependent: :destroy

  acts_as_follower
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  

  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :set_group

def create  
  @comment = @group.comments.build(comment_params)
  @comment.user_id = current_user.id

  if @comment.save
    flash[:success] = "You commented the hell out of that post!"
    redirect_to group_path(@group)
  else
    flash[:alert] = "Check the comment form, something went horribly wrong."
    render root_path
  end
end

def destroy  
  @comment = @group.comments.find(params[:id])

  @comment.destroy
  flash[:success] = "Comment deleted :("
  redirect_to root_path
end  

private

def comment_params  
  params.require(:comment).permit(:content)
end

def set_group  
  @group = Group.find(params[:group_id])
end  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    before_action :authenticate_user!  

    def index
        @groups = Group.all
        @user_lat = request.location.latitude
        @user_lon = request.location.longitude
    end

    def new
        @group = Group.new
    end

    def create
        @group_lat = 1
        @group_lon = 2

        @group = Group.create(group_params)
        @group.update_attributes({:latitude => @group_lat,:longitude => @group_lon, :author => current_user.user_name,:author_id => current_user.id})
        redirect_to groups_path
    end

    def show
        @group = Group.find(params[:id])
    end

    def destroy
        @group = Group.find(params[:id])
        @group.delete
        redirect_to groups_path
    end

    private def group_params
        params.require(:group).permit(:name,:category,:description)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :bio)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end  

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!  

    def show
        if current_user
            @user = User.find(params[:id])
        else
            redirect_to '/users/sign_in'
        end
    end

    def follow
			current_user.follow(Group.find(params[:id]))
			redirect_to group_path(params[:id])
	end

	def unfollow
			current_user.stop_following(Group.find(params[:id]))
			redirect_to group_path(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<h1>Groups Near You</h1>
<div class="posts-wrapper row">
  <% @groups.each do |group| %>
    <div class="post">
      <div class="post-head">
        <div class="name">
          <%= link_to group.name, group_path(group) %>
        </div>
      </div>
      <p class="caption">
        <%= group.category %>
      </p>
    </div>
  <% end %>
</div>

app/views/groups/new.html.erb

<div class="form-wrapper">
  <%= simple_form_for @group, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group text-center">
      <%= f.input :name %>
    </div>
    <div class="form-group text-center">
      <%= f.input :category, collection: ["Recreational", "Education", "Parenting", "Counseling", "Lifestyle", "Other"] %>
    </div>
    <div class="form-group text-center">
      <%= f.label :description %> </br>
      <%= f.text_area :description, :cols => "50", :rows => "10" %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success' %>
    </div>
  <% end %>
</div>

app/views/groups/show.html.erb

<% if current_user.user_name == @group.author%>
    <div id = "delete-link" class = "link"> <%= link_to 'Delete Group', group_path(@group), method: :delete %></div>
<% else %>
    <% if current_user.following?(@group) %>
            <div id = "unfollow-link" class = "link"><%= link_to 'Leave Group', unfollow_users_path(@group.id), method: :post %></div>
        <% else %>
            <div id = "follow-link" class = "link"><%= link_to 'Join Group', follow_users_path(@group.id), method: :post %></div>
    <% end %>
<% end %>

<h1><%= @group.name %></h1>
<h2>Created By <%= link_to @group.author, user_path(@group.author_id) %></h2>
<h3>Number of Members: <%= @group.followers_count %></h3>
<% @group.followers.each do |follower| %>
	<div><%= link_to follower.user_name, user_path(follower.id) %></div>
<% end %>

<h2>Group Description:</h2>
<p><%= @group.description %></p>

    <% if @group.comments %>
        <% @group.comments.each do |comment| %>
        <div class="comment">
            <h3>
             <%= comment.user.user_name %>
             </h3>
             <h4>
            <%= comment.content %>
           </h4>
           <% if comment.user == current_user %>
            <%= link_to "Delete Comment", group_comment_path(@group, comment), method: :delete %>
          <% end %>
         </div>
       <% end %>
       <% end %>
       <div class="comment-form">
     <%= form_for [@group, @group.comments.new] do |f| %>
         <%= f.text_field :content, placeholder: 'Add a comment...' %>
       <% end %>
      </div>

 
  


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geelink</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<nav class="navbar navbar-default">
  <div class="navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to "GeeLink", root_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.present? %>
          <li>
            <%= link_to "New Group", new_group_path %>
          </li>
          <li>
            <%= link_to('Profile', user_path(current_user.id)) %>
          </li>
          <li>
              <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
         </li>
        <% else %>
          <li>
                <%= link_to('Login', new_user_session_path)  %>  
          </li>
          <li>
                <%= link_to('Register', new_user_registration_path) %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>


  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
	
</head>
<body>
	<h1>
		User Profile
	</h1>
	<h2>
		<%= @user.user_name %>
	</h2>
	<p>
		<i><%= @user.email %></i>
	</p>
	<h3>
		Groups:
	</h3>
		<% @user.all_following.each do |following| %>
			<% if following %>
				<div><%= link_to following.name, group_path(following.id) %></div>
			<% end %>
		<% end %>
	<h3>
		User Bio:
	</h3>
	<p>
		<%= @user.bio %>
	</p>
</body>
</html>